/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
static yyconst short int yy_acclist[415] =
    {   0,
       55,   53,   54,    2,   53,   54,    3,   54,   49,   53,
       54,    6,   53,   54,   47,   53,   54,   49,   53,   54,
       11,   53,   54,   26,   53,   54,   31,   53,   54,   47,
       53,   54,   47,   53,   54,   36,   53,   54,   47,   53,
       54,   39,   53,   54,   47,   53,   54,   25,   53,   54,
       25,   53,   54,   51,   53,   54,   35,   53,   54,   48,
       53,   54,   52,   53,   54,   48,   53,   54,   17,   53,
       54,   32,   53,   54,   33,   53,   54,   49,   53,   54,
       17,   53,   54,   17,   53,   54,   17,   53,   54,   17,
       53,   54,   17,   53,   54,   17,   53,   54,   17,   53,

       54,   17,   53,   54,   17,   53,   54,   17,   53,   54,
       17,   53,   54,   17,   53,   54,   17,   53,   54,   17,
       53,   54,   17,   53,   54,   17,   53,   54,   37,   53,
       54,   50,   53,   54,   38,   53,   54,   49,   53,   54,
        2,   53,   54,    1,   53,   54,   54,   10,   54,    9,
       54,   10,   54,   14,   54,   13,   54,   14,   54,   27,
       54,   30,   54,   28,   54,   29,   54,    2,   44,   41,
       46,   42,   40,   39,   22,    5,    4,   21,   24,   25,
       25,   25,   25,   45,   45,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,

       15,   17,   17,   17,   17,   17,   17,   17,   15,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,    2,    1,    1,    7,   27,   22,    4,   20,   21,
       24,   25,   24,   25,   19,   23,   25,   25,   25,   18,
       43,   34,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   16,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,    1,    8,   12,   22,   20,   21,   24,   25,
       24,   25,   24,   25,   19,   19,   23,   25,   25,   18,

       18,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,    1,   20,   24,   25,   24,   25,   19,   19,
       19,   18,   18,   18,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   19,   19,
       18,   18,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17
    } ;

static yyconst short int yy_accept[342] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    4,    7,    9,   12,   15,   18,
       21,   24,   27,   30,   33,   36,   39,   42,   45,   48,
       51,   54,   57,   60,   63,   66,   69,   72,   75,   78,
       81,   84,   87,   90,   93,   96,   99,  102,  105,  108,
      111,  114,  117,  120,  123,  126,  129,  132,  135,  138,
      141,  144,  147,  148,  150,  152,  154,  156,  158,  160,
      162,  164,  166,  168,  169,  170,  171,  172,  173,  174,
      175,  176,  177,  178,  179,  181,  182,  182,  182,  183,
      184,  184,  185,  186,  187,  187,  187,  188,  189,  190,

      191,  192,  193,  194,  195,  196,  197,  198,  199,  200,
      201,  203,  204,  205,  206,  207,  208,  209,  211,  212,
      213,  214,  215,  216,  217,  218,  219,  220,  221,  222,
      223,  224,  225,  225,  225,  226,  226,  226,  226,  227,
      227,  228,  229,  230,  230,  231,  233,  235,  236,  236,
      237,  238,  239,  240,  241,  242,  242,  243,  244,  245,
      246,  247,  248,  249,  250,  251,  252,  253,  254,  255,
      256,  257,  258,  259,  260,  261,  262,  263,  264,  265,
      267,  268,  269,  270,  271,  272,  273,  274,  275,  276,
      277,  278,  279,  280,  281,  282,  283,  284,  285,  285,

      285,  286,  286,  286,  286,  287,  287,  288,  288,  289,
      291,  293,  295,  296,  297,  298,  299,  300,  301,  302,
      303,  304,  305,  306,  307,  308,  309,  310,  311,  312,
      313,  314,  315,  316,  317,  318,  319,  320,  321,  322,
      323,  324,  325,  326,  327,  328,  329,  330,  331,  332,
      333,  334,  334,  334,  334,  334,  334,  335,  337,  339,
      340,  341,  342,  343,  344,  345,  346,  347,  348,  349,
      350,  351,  352,  353,  354,  355,  356,  357,  358,  359,
      360,  361,  362,  363,  364,  365,  366,  367,  368,  369,
      369,  369,  369,  369,  370,  371,  372,  373,  374,  375,

      376,  377,  378,  379,  380,  381,  382,  383,  384,  385,
      386,  387,  388,  389,  390,  391,  392,  393,  394,  395,
      396,  397,  398,  399,  400,  401,  402,  403,  404,  405,
      406,  407,  408,  409,  410,  411,  412,  413,  414,  415,
      415
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   36,   36,   38,   36,   39,   36,   36,
       36,   36,   40,   41,   42,   36,   36,   43,   36,   36,
       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   36,   58,   59,   60,   61,
       62,   63,   36,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[77] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        5,    5,    1,    1,    1,    1,    1,    1,    6,    6,
        6,    7,    1,    1,    1,    1,    1,    3,    7,    7,
        7,    7,    7,    7,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    1,    3,    1,    1,    8,    6,    6,
        7,    7,    7,    6,    8,    8,    8,    8,    8,    8,
        9,    8,    8,    9,    8,    9,    8,    9,    8,    9,
        8,    8,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[357] =
    {   0,
        0,   75,    0,    0,   75,   77,   76,   81,    0,    0,
       82,   84,  747,  748,   86,  748,  720,  748,  719,   80,
      748,  748,  748,  718,   78,  748,   81,   79,   92,  102,
       95,  748,  748,   77,  717,   99,    0,  137,  748,  716,
      136,  674,  676,   80,   58,   90,   68,  677,   77,  676,
      684,  122,  665,  674,  672,  677,  748,  108,  748,  748,
      179,  687,  748,  748,  748,  140,  748,  748,  686,    0,
      748,  748,  748,  166,  748,  748,  748,  748,  748,  748,
      173,  748,    0,  180,  202,  226,  144,  251,  170,  115,
        0,  704,  703,    0,  256,  278,   84,  666,  665,  673,

      665,  662,  657,  666,  655,  667,  654,  669,  656,  662,
      648,  649,  646,  646,  649,  646,  643,    0,  121,  647,
      150,  645,  148,  140,  649,  642,  133,  171,  647,  234,
      658,  657,  698,  204,  748,  271,  186,  231,    0,  267,
      748,    0,  283,  292,  748,  280,  204,  290,  324,  331,
      142,  748,  256,  281,  748,  325,  748,  643,  637,  636,
      637,  635,  646,  630,  644,  628,  629,  641,  636,  624,
      188,  638,  636,  632,  624,  630,  633,  619,  623,    0,
      624,  621,  611,  609,  611,  613,  620,  606,  604,  604,
      616,  606,  610,  614,  616,  605,  618,  748,  314,    0,

      748,  353,    0,  356,  361,  372,  748,  381,  385,  288,
      748,  320,  370,  328,  748,  748,  748,  371,  330,  607,
      601,  601,  585,  592,  589,  589,  572,  584,  577,  556,
      559,  546,  547,  540,  529,  525,  473,  473,  472,  468,
      480,  470,  474,  479,  478,  476,  466,  471,  459,  465,
      472,  405,  445,  412,  490,  421,  434,  748,  748,  289,
      748,  358,  368,  748,  359,  455,  458,  455,  449,  451,
      441,  449,  456,  443,  444,  449,  440,  439,  425,  432,
      426,  434,  431,  433,  417,  426,  428,  419,  416,  211,
        0,  315,    0,  748,  748,  748,  748,  305,  420,  417,

      412,  402,  395,  410,  408,  392,  392,  399,  398,  394,
      394,  387,  380,  382,  364,  377,  378,  357,  368,  366,
      331,  306,  298,  310,  308,  274,  265,  258,  237,  224,
      219,  204,  197,  206,  172,  148,   83,   54,   43,  748,
      544,  553,  562,  571,  575,  584,  593,  602,  611,  620,
      624,  630,  637,  646,  650,  652
    } ;

static yyconst short int yy_def[357] =
    {   0,
      340,    1,  341,  341,  342,  342,  343,  343,  341,  341,
      344,  344,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  345,  340,  340,  340,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  340,  340,  340,  340,
      340,  346,  340,  340,  340,  347,  340,  340,  348,  349,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  350,  340,  340,  340,  340,  340,  340,  340,
      351,  340,  340,  345,  340,  340,  345,  345,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  340,
      346,  346,  340,  347,  340,  352,  348,  353,  349,  340,
      340,  350,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  351,  340,  340,  340,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  354,  340,  347,  355,

      340,  348,  356,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      354,  347,  347,  348,  348,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  347,
      253,  348,  255,  340,  340,  340,  340,  345,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,    0,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340
    } ;

static yyconst short int yy_nxt[825] =
    {   0,
       14,   15,   16,   15,   17,   18,   14,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       31,   31,   32,   33,   34,   35,   36,   32,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   38,   14,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   37,   49,   37,   50,   37,
       37,   37,   37,   51,   52,   53,   54,   55,   56,   37,
       37,   37,   57,   58,   59,   60,   61,   65,   68,   65,
       66,   62,   66,   68,   71,   69,   71,   74,   77,   74,
       69,   79,   72,   73,   72,   73,   79,   81,   81,   81,

       81,   92,   75,   76,   82,   78,   76,   80,  118,   83,
      110,   84,  118,   86,   86,   86,   86,   76,   84,  111,
       85,   85,   85,   86,   75,   93,  115,   88,  107,  116,
      118,   87,   89,   78,   88,  108,   90,  119,   95,   89,
       95,  109,  158,   90,   91,  135,  339,   88,  112,  159,
      113,   87,  153,   89,   88,   96,   96,   96,   96,  114,
       89,   90,  148,  148,   97,   98,   99,   74,   90,   74,
      100,   91,  101,  153,  102,  103,  104,  122,  123,  179,
      130,   77,   74,  216,  136,  131,  180,  124,  188,  192,
      125,   81,   81,   81,   81,  201,  338,  193,  143,  143,

      143,  143,  186,  189,  182,  140,  141,  151,  216,  135,
      141,  152,  144,  145,  183,  184,  135,  145,   84,  187,
       85,   85,   85,   86,  337,  140,  141,  194,  151,  195,
      138,  141,  144,  145,   88,  130,  152,   74,  145,  146,
      131,  212,   84,  147,   86,   86,   86,   86,  136,  202,
      202,  202,  230,  231,   88,  136,  336,   95,   88,   95,
      146,  335,  212,   89,  149,  334,  149,   90,  147,  150,
      150,  150,  150,  198,   96,   96,   96,   96,   88,  156,
      204,  156,  204,  333,   89,  205,  205,  205,  205,  199,
      199,  199,   90,  217,  118,  332,   96,   96,   96,   96,

      203,  143,  143,  143,  143,  208,  331,  208,  148,  148,
      209,  209,  209,  209,  217,  206,  207,  210,  218,  135,
      207,  211,  219,  157,  201,  118,  156,  213,  156,  258,
      294,  214,  252,  252,  252,  206,  207,  330,  210,  218,
      200,  207,  150,  150,  150,  150,  211,  219,  213,  150,
      150,  150,  150,  313,  258,  294,  214,  259,  136,  138,
      118,  180,  201,  118,  215,  262,  314,  265,  215,  118,
      157,  254,  254,  254,  205,  205,  205,  205,  259,  205,
      205,  205,  205,  118,  215,  256,  262,  256,  265,  215,
      257,  257,  257,  257,  141,  295,  297,  138,  141,  209,

      209,  209,  209,  209,  209,  209,  209,  260,  263,  296,
      135,  261,  264,  329,  141,  328,  295,  297,  145,  141,
      327,  201,  145,  290,  290,  290,  326,  118,  260,  263,
      292,  292,  292,  118,  296,  118,  261,  264,  145,  257,
      257,  257,  257,  145,  118,  325,  324,  118,  323,  136,
      135,  322,  257,  257,  257,  257,  138,  118,  321,  320,
      319,  318,  317,  291,  291,  291,  291,  207,  316,  315,
      118,  207,  312,  291,  291,  291,  291,  291,  291,  311,
      310,  118,  118,  118,  118,  180,  118,  207,  309,  136,
      308,  118,  207,  291,  291,  291,  291,  291,  291,  201,

      118,  180,  307,  306,  305,  304,  303,  302,  293,  293,
      293,  293,  301,  300,  299,  298,  133,  118,  293,  293,
      293,  293,  293,  293,  289,  288,  118,  287,  286,  285,
      284,  283,  282,  180,  138,  281,  280,  279,  293,  293,
      293,  293,  293,  293,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       94,   94,   94,   94,  132,  278,  132,  132,  132,  132,
      132,  132,  132,  134,  180,  134,  134,  134,  134,  134,

      134,  134,  137,  277,  137,  276,  137,  137,  137,  137,
      137,  139,  275,  139,  139,  274,  139,  139,  139,  139,
      142,  118,  142,  142,  142,  142,  142,  142,  142,  154,
      154,  134,  134,  134,  118,  134,  273,  272,  134,  137,
      137,  271,  137,  270,  269,  137,  251,  268,  251,  251,
      251,  251,  251,  251,  251,  253,  253,  255,  255,  118,
      267,  266,  133,  250,  249,  180,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  180,  236,
      118,  235,  234,  118,  118,  233,  232,  180,  118,  229,
      118,  228,  227,  226,  225,  224,  223,  222,  221,  220,

      197,  133,  133,  196,  191,  190,  185,  181,  178,  118,
      177,  176,  175,  174,  173,  172,  171,  170,  169,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  155,  155,
      138,  133,  129,  128,  127,  126,  121,  120,  117,  106,
      105,   78,   75,   76,   76,   75,  340,   13,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,

      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340
    } ;

static yyconst short int yy_chk[825] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    5,    7,    6,
        5,    2,    6,    8,   11,    7,   12,   15,   20,   15,
        8,   25,   11,   11,   12,   12,   27,   28,   28,   28,

       28,   34,   34,   25,   29,   20,   27,   27,  339,   29,
       45,   31,  338,   31,   31,   31,   31,   29,   30,   45,
       30,   30,   30,   30,   36,   36,   47,   31,   44,   47,
       49,   30,   31,   58,   30,   44,   31,   49,   38,   30,
       38,   44,   97,   30,   30,   66,  337,   31,   46,   97,
       46,   30,   90,   31,   30,   38,   38,   38,   38,   46,
       30,   31,   87,   87,   41,   41,   41,   74,   30,   74,
       41,   30,   41,   90,   41,   41,   41,   52,   52,  119,
       61,   58,   61,  151,   66,   61,  119,   52,  124,  127,
       52,   81,   81,   81,   81,  137,  336,  127,   84,   84,

       84,   84,  123,  124,  121,   81,   81,   89,  151,  134,
       81,   89,   84,   84,  121,  121,  290,   84,   85,  123,
       85,   85,   85,   85,  335,   81,   81,  128,   89,  128,
      137,   81,   84,   84,   85,  130,   89,  130,   84,   85,
      130,  147,   86,   85,   86,   86,   86,   86,  134,  138,
      138,  138,  171,  171,   85,  290,  334,   95,   86,   95,
       85,  333,  147,   86,   88,  332,   88,   86,   85,   88,
       88,   88,   88,  136,   95,   95,   95,   95,   86,   96,
      140,   96,  140,  331,   86,  140,  140,  140,  140,  136,
      136,  136,   86,  153,  330,  329,   96,   96,   96,   96,

      138,  143,  143,  143,  143,  144,  328,  144,  148,  148,
      144,  144,  144,  144,  153,  143,  143,  146,  154,  199,
      143,  146,  154,   96,  292,  327,  156,  148,  156,  210,
      260,  148,  199,  199,  199,  143,  143,  326,  146,  154,
      136,  143,  149,  149,  149,  149,  146,  154,  148,  150,
      150,  150,  150,  298,  210,  260,  148,  212,  199,  292,
      325,  324,  202,  323,  150,  214,  298,  219,  150,  322,
      156,  202,  202,  202,  204,  204,  204,  204,  212,  205,
      205,  205,  205,  321,  150,  206,  214,  206,  219,  150,
      206,  206,  206,  206,  205,  262,  265,  202,  205,  208,

      208,  208,  208,  209,  209,  209,  209,  213,  218,  263,
      252,  213,  218,  320,  205,  319,  262,  265,  209,  205,
      318,  254,  209,  252,  252,  252,  317,  316,  213,  218,
      254,  254,  254,  315,  263,  314,  213,  218,  209,  256,
      256,  256,  256,  209,  313,  312,  311,  310,  309,  252,
      253,  308,  257,  257,  257,  257,  254,  307,  306,  305,
      304,  303,  302,  253,  253,  253,  253,  257,  301,  300,
      299,  257,  289,  253,  253,  253,  253,  253,  253,  288,
      287,  286,  285,  284,  283,  282,  281,  257,  280,  253,
      279,  278,  257,  253,  253,  253,  253,  253,  253,  255,

      277,  276,  275,  274,  273,  272,  271,  270,  255,  255,
      255,  255,  269,  268,  267,  266,  251,  250,  255,  255,
      255,  255,  255,  255,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  255,  239,  238,  237,  255,  255,
      255,  255,  255,  255,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      345,  345,  345,  345,  346,  236,  346,  346,  346,  346,
      346,  346,  346,  347,  235,  347,  347,  347,  347,  347,

      347,  347,  348,  234,  348,  233,  348,  348,  348,  348,
      348,  349,  232,  349,  349,  231,  349,  349,  349,  349,
      350,  230,  350,  350,  350,  350,  350,  350,  350,  351,
      351,  352,  352,  352,  229,  352,  228,  227,  352,  353,
      353,  226,  353,  225,  224,  353,  354,  223,  354,  354,
      354,  354,  354,  354,  354,  355,  355,  356,  356,  222,
      221,  220,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  179,
      178,  177,  176,  175,  174,  173,  172,  170,  169,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  158,

      133,  132,  131,  129,  126,  125,  122,  120,  117,  116,
      115,  114,  113,  112,  111,  110,  109,  108,  107,  106,
      105,  104,  103,  102,  101,  100,   99,   98,   93,   92,
       69,   62,   56,   55,   54,   53,   51,   50,   48,   43,
       42,   40,   35,   24,   19,   17,   13,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,

      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexicalAnalyzer/src/scanner.l"
#define INITIAL 0
#line 5 "lexicalAnalyzer/src/scanner.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

static char* xstrdup(const char* s){
    if(!s) return NULL;
    size_t n=strlen(s)+1; char* p=(char*)malloc(n); if(p) memcpy(p,s,n); return p;
}
static char* xsubstr(const char* s, size_t a, size_t b){
    if(!s||b<a) return xstrdup("");
    size_t n=b-a; char* p=(char*)malloc(n+1); if(!p) return NULL;
    memcpy(p,s+a,n); p[n]='\0'; return p;
}
static char* trim(char* s){
    if(!s) return s;
    size_t n=strlen(s);
    size_t i=0; while(i<n && isspace((unsigned char)s[i])) i++;
    size_t j=n; while(j>i && isspace((unsigned char)s[j-1])) j--;
    size_t m=j-i; memmove(s, s+i, m); s[m]='\0'; return s;
}
static int is_ident_start_c(unsigned char c){ return (c=='_' || isalpha(c)); }
static int is_ident_char_c (unsigned char c){ return (c=='_' || isalnum(c)); }

typedef struct Symbol {
    char* name;
    char* type;            /* e.g., int, float, char*, struct X */
    char* dimensions;      /* e.g., [10][20] */
    int   frequency;       /* number of appearances */
    char* return_type;     /* for functions */
    char* param_lists;     /* concatenated lists observed in function calls or declarations */
    int   is_function;     /* boolean */
    struct Symbol* next;   /* chaining in hash bucket */
} Symbol;

#define SYM_HASH_SIZE 211
static Symbol* symtab[SYM_HASH_SIZE];

static unsigned long djb2(const char* str){
    unsigned long hash = 5381; int c;
    while((c = (unsigned char)*str++)) hash = ((hash << 5) + hash) + c;
    return hash;
}
static Symbol* sym_lookup(const char* name){
    unsigned long h = djb2(name) % SYM_HASH_SIZE;
    Symbol* s = symtab[h];
    while(s){ if(strcmp(s->name, name)==0) return s; s=s->next; }
    return NULL;
}
static Symbol* sym_insert(const char* name){
    unsigned long h = djb2(name) % SYM_HASH_SIZE;
    Symbol* s = (Symbol*)calloc(1, sizeof(Symbol));
    s->name = xstrdup(name);
    s->frequency = 0;
    s->next = symtab[h];
    symtab[h] = s;
    return s;
}
static Symbol* sym_touch(const char* name){
    Symbol* s = sym_lookup(name);
    if(!s) s = sym_insert(name);
    s->frequency++;
    return s;
}
static void sym_set_type(Symbol* s, const char* type){
    if(!s) return;
    if(s->type) free(s->type);
    s->type = xstrdup(type);
}
static void sym_set_return(Symbol* s, const char* r){
    if(!s) return;
    if(s->return_type) free(s->return_type);
    s->return_type = xstrdup(r);
}
static void sym_append_dims(Symbol* s, const char* dims){
    if(!s || !dims) return;
    size_t old = s->dimensions ? strlen(s->dimensions) : 0;
    size_t add = strlen(dims);
    char* p = (char*)malloc(old + add + 1);
    if(!p) return;
    if(old){ memcpy(p, s->dimensions, old); free(s->dimensions); }
    memcpy(p+old, dims, add);
    p[old+add]='\0';
    s->dimensions = p;
}
static void sym_append_params(Symbol* s, const char* params){
    if(!s || !params) return;
    const char* sep = s->param_lists ? " ; " : "";
    size_t old = s->param_lists ? strlen(s->param_lists) : 0;
    size_t add = strlen(sep) + strlen(params);
    char* p = (char*)malloc(old + add + 1);
    if(!p) return;
    if(old){ memcpy(p, s->param_lists, old); free(s->param_lists); }
    memcpy(p+old, sep, strlen(sep));
    memcpy(p+old+strlen(sep), params, strlen(params));
    p[old+add]='\0';
    s->param_lists = p;
}

typedef struct Constant {
    char* var_name;  /* For #define NAME value, or variable name for other constants */
    int   line;
    char* value;     /* literal text */
    char* type;      /* "int", "float", "char", "string", "hex", "oct", "bin", "macro" */
} Constant;

static Constant* consts = NULL;
static size_t nconsts = 0, capconsts = 0;

static void const_add(const char* var, int line, const char* val, const char* type){
    if(nconsts == capconsts){
        capconsts = capconsts ? capconsts*2 : 64;
        consts = (Constant*)realloc(consts, capconsts * sizeof(Constant));
    }
    consts[nconsts].var_name = xstrdup(var ? var : "-");
    consts[nconsts].line = line;
    consts[nconsts].value = xstrdup(val ? val : "");
    consts[nconsts].type = xstrdup(type ? type : "");
    nconsts++;
}

static int in_declaration = 0;
static char last_type[256] = {0};
static char last_ident[256] = {0};
static int last_was_ident = 0;
static int array_capture_for_ident = 0;
static int brace_depth = 0;
static int assignment_context = 0;  /* Track if we're in an assignment */
static char pending_var[256] = {0}; /* Variable name for pending constant assignment */

static void start_declaration(const char* t){
    in_declaration = 1;
    last_type[0]='\0';
    if(t){ strncat(last_type, t, sizeof(last_type)-1); }
}
static void add_type_token(const char* t){
    if(last_type[0]) strncat(last_type, " ", sizeof(last_type)-1);
    strncat(last_type, t, sizeof(last_type)-1);
}
static void end_declaration(){
    in_declaration = 0;
    last_type[0]='\0';
    assignment_context = 0;
    pending_var[0] = '\0';
    array_capture_for_ident = 0;
}

static int paren_depth = 0;
static int capturing_args = 0;
static char* arg_buffer = NULL;
static size_t arg_cap = 0, arg_len = 0;
static Symbol* current_func_sym = NULL;

static void args_begin(Symbol* s){
    capturing_args = 1; paren_depth = 1; arg_len = 0;
    if(!arg_buffer){ arg_cap = 256; arg_buffer = (char*)malloc(arg_cap); }
    current_func_sym = s;
}
static void args_push_char(int c){
    if(!capturing_args) return;
    if(arg_len + 2 > arg_cap){
        arg_cap = arg_cap ? arg_cap*2 : 256;
        arg_buffer = (char*)realloc(arg_buffer, arg_cap);
    }
    arg_buffer[arg_len++] = (char)c;
    arg_buffer[arg_len] = '\0';
}

/* helper: find start index of last identifier in s, or -1 if none */
static int find_last_ident_pos(const char* s){
    if(!s) return -1;
    int i = (int)strlen(s) - 1;
    while(i >= 0){
        if(is_ident_char_c((unsigned char)s[i])){
            int end = i;
            int j = i;
            while(j >= 0 && is_ident_char_c((unsigned char)s[j])) j--;
            /* Now identifier is s[j+1 .. end] */
            return j+1;
        }
        i--;
    }
    return -1;
}

/* Parse arg_buffer to assign parameter types to symbols */
static void parse_and_register_params(const char* params_text){
    if(!params_text || !*params_text) return;

    int depth = 0; /* for nested parens (function pointers) */
    size_t n = strlen(params_text);
    size_t start = 0;

    for(size_t i=0; i<=n; ++i){
        int is_end = (i==n);
        char c = is_end ? ',' : params_text[i];

        if(!is_end){
            if(c=='(') depth++;
            else if(c==')' && depth>0) depth--;
        }
        if(c==',' && depth==0 || is_end){
            /* segment = params_text[start..i) */
            char* seg = xsubstr(params_text, start, i);
            trim(seg);
            if(seg[0]){
                /* skip 'void' and '...' */
                if(!(strcmp(seg,"void")==0 || strcmp(seg,"...")==0)){
                    int pos = find_last_ident_pos(seg);
                    if(pos >= 0){
                        /* name is seg[pos..] until non-ident */
                        int k = pos;
                        while(seg[k] && is_ident_char_c((unsigned char)seg[k])) k++;
                        char saved = seg[k];
                        seg[k] = '\0';
                        const char* name = seg + pos;

                        /* type is seg[0..pos) trimmed */
                        char* tpart = xsubstr(seg, 0, pos);
                        trim(tpart);

                        /* Touch symbol and set type if unknown */
                        Symbol* s = sym_touch(name);
                        if(tpart[0] && (!s->type || s->type[0]=='\0')){
                            sym_set_type(s, tpart);
                        }

                        /* restore and cleanup */
                        seg[k] = saved;
                        free(tpart);
                    }
                }
            }
            free(seg);
            start = i+1;
        }
    }
}

static void args_end(){
    if(capturing_args && current_func_sym){
        /* remove trailing ) if present */
        if(arg_len && arg_buffer[arg_len-1] == ')'){ arg_buffer[arg_len-1] = '\0'; }
        char* s = xstrdup(arg_buffer);
        trim(s);
        sym_append_params(current_func_sym, s);
        current_func_sym->is_function = 1;

        /* NEW: parse parameter text and assign types to parameter symbols */
        parse_and_register_params(s);

        free(s);
    }
    capturing_args = 0; paren_depth = 0; arg_len = 0; current_func_sym = NULL;
}

static void print_token(const char* kind, const char* lexeme){
    printf("[line %d] %-12s : %s\n", yylineno, kind, lexeme);
}

static const char* classify_int(const char* s){
    if(!s) return "int";
    if(strlen(s) > 2 && s[0]=='0' && (s[1]=='x'||s[1]=='X')) return "hex";
    if(strlen(s) > 2 && s[0]=='0' && (s[1]=='b'||s[1]=='B')) return "bin";
    if(s[0]=='0' && strlen(s)>1) return "oct";
    return "int";
}

#define YY_USER_ACTION /* placeholder */

#define COMMENT 1

#define STRING 2

#define CHARLIT 3

#define PP 4

#define FUNCARGS 5

#line 1004 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 301 "lexicalAnalyzer/src/scanner.l"


#line 1161 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 341 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 748 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 303 "lexicalAnalyzer/src/scanner.l"
{
    print_token("PREPROC", yytext);
    char* tmp = xstrdup(yytext);
    char* p = tmp;
    while(*p==' '||*p=='\t') p++;
    if(*p=='#'){ p++; }
    while(*p==' ') p++;
    if(strncmp(p,"define",6)==0 && isspace((unsigned char)p[6])){
        p+=6; while(*p==' ') p++;
        char namebuf[256]={0};
        int i=0;
        while(*p && (isalnum((unsigned char)*p) || *p=='_')){
            if(i<255) namebuf[i++]=*p;
            p++;
        }
        namebuf[i]='\0';
        while(*p==' '||*p=='\t') p++;
        char* val = trim(p);
        if(val && namebuf[0]){
            const_add(namebuf, yylineno, val, "macro");
        }
    }
    free(tmp);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 328 "lexicalAnalyzer/src/scanner.l"
{ /* ignore */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 329 "lexicalAnalyzer/src/scanner.l"
{ /* newline handled by %option yylineno */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 331 "lexicalAnalyzer/src/scanner.l"
{ /* ignore */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 333 "lexicalAnalyzer/src/scanner.l"
{
             BEGIN(COMMENT); int depth=1; int c1,c2;
             while(depth>0){
                c1 = input();
                if(c1==EOF){ fprintf(stderr,"[line %d] ERROR: Unterminated comment\n", yylineno); BEGIN(INITIAL); break; }
                if(c1=='\n'){ yylineno++; }  /* advance line count manually here */
                if(c1=='/'){
                    c2 = input();
                    if(c2=='*'){ depth++; }
                    else if(c2!=EOF){ unput(c2); }
                } else if(c1=='*'){
                    c2 = input();
                    if(c2=='/'){ depth--; }
                    else if(c2!=EOF){ unput(c2); }
                }
             }
             BEGIN(INITIAL);
           }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 352 "lexicalAnalyzer/src/scanner.l"
{ BEGIN(STRING); yyless(0); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 353 "lexicalAnalyzer/src/scanner.l"
{
             print_token("STRING", yytext);
             const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
             const_add(var_name, yylineno, yytext, "string");
             if(assignment_context) assignment_context = 0;
             BEGIN(INITIAL);
           }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 360 "lexicalAnalyzer/src/scanner.l"
{ /* continued line inside string */ }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 361 "lexicalAnalyzer/src/scanner.l"
{ fprintf(stderr,"[line %d] ERROR: Unterminated string literal\n", yylineno-1); BEGIN(INITIAL); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 362 "lexicalAnalyzer/src/scanner.l"
{ /* consume */ }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 364 "lexicalAnalyzer/src/scanner.l"
{ BEGIN(CHARLIT); yyless(0); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 365 "lexicalAnalyzer/src/scanner.l"
{
             print_token("CHAR", yytext);
             const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
             const_add(var_name, yylineno, yytext, "char");
             if(assignment_context) assignment_context = 0;
             BEGIN(INITIAL);
           }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 372 "lexicalAnalyzer/src/scanner.l"
{ fprintf(stderr,"[line %d] ERROR: Unterminated char literal\n", yylineno-1); BEGIN(INITIAL); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 373 "lexicalAnalyzer/src/scanner.l"
{ /* consume */ }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 375 "lexicalAnalyzer/src/scanner.l"
{
    print_token("KEYWORD", yytext);
    last_was_ident = 0;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 380 "lexicalAnalyzer/src/scanner.l"
{
    print_token("TYPE", yytext);
    if(!in_declaration) start_declaration(yytext);
    else add_type_token(yytext);
    last_was_ident = 0;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 387 "lexicalAnalyzer/src/scanner.l"
{
    print_token("IDENT", yytext);
    Symbol* s = sym_touch(yytext);
    strncpy(last_ident, yytext, sizeof(last_ident)-1);
    last_ident[sizeof(last_ident)-1]='\0';
    last_was_ident = 1;

    /* Only allow array-dimension capture during declarations */
    array_capture_for_ident = in_declaration ? 1 : 0;

    if(in_declaration){
        if(!s->type && last_type[0]) sym_set_type(s, last_type);
    }
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 402 "lexicalAnalyzer/src/scanner.l"
{
    print_token("NUMBER", yytext);
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, "hex");
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 409 "lexicalAnalyzer/src/scanner.l"
{
    print_token("NUMBER", yytext);
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, "bin");
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 416 "lexicalAnalyzer/src/scanner.l"
{
    print_token("NUMBER", yytext);
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, "float");
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 423 "lexicalAnalyzer/src/scanner.l"
{
    print_token("NUMBER", yytext);
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, "float");
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 430 "lexicalAnalyzer/src/scanner.l"
{
    print_token("NUMBER", yytext);
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, "float");
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 437 "lexicalAnalyzer/src/scanner.l"
{
    print_token("NUMBER", yytext);
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, "float");
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 444 "lexicalAnalyzer/src/scanner.l"
{
    print_token("NUMBER", yytext);
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, "oct");
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 451 "lexicalAnalyzer/src/scanner.l"
{
    print_token("NUMBER", yytext);
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, classify_int(yytext));
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 459 "lexicalAnalyzer/src/scanner.l"
{
            print_token("PUNCT", yytext);
            if(last_was_ident){
                Symbol* s = sym_lookup(last_ident);
                if(!s) s = sym_touch(last_ident);
                if(in_declaration || brace_depth == 0){
                    s->is_function = 1;
                    if(last_type[0]) sym_set_return(s, last_type);
                }
                args_begin(s);
                BEGIN(FUNCARGS);
            }
            last_was_ident = 0;
         }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 473 "lexicalAnalyzer/src/scanner.l"
{ for(size_t i=0;i<(size_t)yyleng;i++) args_push_char(yytext[i]); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 474 "lexicalAnalyzer/src/scanner.l"
{ args_push_char('('); paren_depth++; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 475 "lexicalAnalyzer/src/scanner.l"
{
    args_push_char(')');
    paren_depth--;
    if (paren_depth == 0) {
        args_end();
        print_token("PUNCT", yytext);
        BEGIN(INITIAL);
    }
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 484 "lexicalAnalyzer/src/scanner.l"
{ args_push_char('\n'); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 486 "lexicalAnalyzer/src/scanner.l"
{ print_token("PUNCT", yytext); last_was_ident = 0; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 488 "lexicalAnalyzer/src/scanner.l"
{ print_token("PUNCT", yytext); last_was_ident = 0; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 489 "lexicalAnalyzer/src/scanner.l"
{ print_token("PUNCT", yytext); last_was_ident = 0; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 491 "lexicalAnalyzer/src/scanner.l"
{
            print_token("PUNCT", yytext);
            if(in_declaration && array_capture_for_ident){
                Symbol* s = sym_lookup(last_ident);
                if(s) sym_append_dims(s, yytext);
            }
            last_was_ident = 0;
         }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 500 "lexicalAnalyzer/src/scanner.l"
{
    print_token("PUNCT", yytext);
    array_capture_for_ident = 0;
    if(in_declaration) end_declaration();
    last_was_ident = 0;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 506 "lexicalAnalyzer/src/scanner.l"
{ print_token("PUNCT", yytext); array_capture_for_ident = 0; last_was_ident = 0; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 507 "lexicalAnalyzer/src/scanner.l"
{ print_token("PUNCT", yytext); brace_depth++; if(in_declaration) end_declaration(); last_was_ident = 0; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 508 "lexicalAnalyzer/src/scanner.l"
{ print_token("PUNCT", yytext); brace_depth--; last_was_ident = 0; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 509 "lexicalAnalyzer/src/scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 511 "lexicalAnalyzer/src/scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 512 "lexicalAnalyzer/src/scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 513 "lexicalAnalyzer/src/scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 514 "lexicalAnalyzer/src/scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 515 "lexicalAnalyzer/src/scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 516 "lexicalAnalyzer/src/scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 517 "lexicalAnalyzer/src/scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 518 "lexicalAnalyzer/src/scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 519 "lexicalAnalyzer/src/scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 520 "lexicalAnalyzer/src/scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 521 "lexicalAnalyzer/src/scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 522 "lexicalAnalyzer/src/scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 523 "lexicalAnalyzer/src/scanner.l"
{
    print_token("OP", yytext);
    array_capture_for_ident = 0; /* definitely not dimensions after '=' */
    if(last_was_ident) {
        assignment_context = 1;
        strncpy(pending_var, last_ident, sizeof(pending_var)-1);
        pending_var[sizeof(pending_var)-1] = '\0';
    }
    last_was_ident = 0;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 534 "lexicalAnalyzer/src/scanner.l"
{ fprintf(stderr, "[line %d] ERROR: Invalid token '%s'\n", yylineno, yytext); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(CHARLIT):
case YY_STATE_EOF(PP):
case YY_STATE_EOF(FUNCARGS):
#line 536 "lexicalAnalyzer/src/scanner.l"
{
            printf("\n************************************* SYMBOL TABLE *************************************\n");
            printf("%-20s %-15s %-12s %-10s %-15s %s\n", "Name", "Type", "Dimensions", "Frequency", "Return Type", "Parameters Lists in Function call");
            for(int i=0;i<SYM_HASH_SIZE;i++){
                for(Symbol* s=symtab[i]; s; s=s->next){
                    printf("%-20s %-15s %-12s %-10d %-15s %s\n",
                        s->name,
                        s->type ? s->type : "-",
                        s->dimensions ? s->dimensions : "-",
                        s->frequency,
                        s->return_type ? s->return_type : (s->is_function ? "unknown" : "-"),
                        s->param_lists ? s->param_lists : "-"
                    );
                }
            }
            printf("\n************************************* CONSTANT TABLE *************************************\n");
            printf("%-20s %-10s %-30s %s\n", "Variable Name", "Line No.", "Value", "Type");
            for(size_t i=0;i<nconsts;i++){
                printf("%-20s %-10d %-30s %s\n",
                    consts[i].var_name ? consts[i].var_name : "-",
                    consts[i].line,
                    consts[i].value ? consts[i].value : "",
                    consts[i].type ? consts[i].type : ""
                );
            }
            return 0;
          }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 564 "lexicalAnalyzer/src/scanner.l"
ECHO;
	YY_BREAK
#line 1721 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 341 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 341 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 340);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 564 "lexicalAnalyzer/src/scanner.l"


int main(int argc, char** argv){
    if(argc > 1){
        FILE* f = fopen(argv[1], "r");
        if(!f){ perror("fopen"); return 1; }
        yyin = f;
    }
    yylex();
    return 0;
}
