
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[345] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   55,   53,    2,    3,   49,    6,   47,   49,
       11,   26,   31,   47,   47,   36,   47,   39,   47,   25,
       25,   51,   35,   48,   52,   48,   17,   32,   33,   49,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   37,   50,   38,   49,
        2,    1,   54,   10,    9,   10,   14,   13,   14,   27,
       30,   28,   29,    2,   44,   41,   46,   42,   40,   39,
       22,    5,    4,   21,   24,   25,    0,    0,   25,   25,
        0,   45,   45,   17,    0,    0,   17,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       15,   17,   17,   17,   17,   17,   17,   15,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,    2,
        1,    1,    0,    0,    7,    0,    0,    0,   27,    0,
       22,    4,   20,    0,   21,   24,   24,   19,    0,   23,
       25,   25,   25,   18,   43,    0,   34,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   16,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,    1,    8,    0,    0,

       12,    0,    0,    0,   22,    0,   20,    0,   21,   24,
       24,   24,   19,   19,   23,   25,   25,   18,   18,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
        1,    0,    0,    0,    0,    0,   20,   24,   24,   19,
       19,   19,   18,   18,   18,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,    0,
        0,    0,    0,   19,   19,   18,   18,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,    0,    0,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    0,    0,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   36,   36,   38,   36,   39,   36,   36,
       36,   36,   40,   41,   42,   36,   36,   43,   36,   36,
       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   36,   58,   59,   60,   61,
       62,   63,   36,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[77] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        5,    5,    1,    1,    1,    1,    1,    1,    6,    6,
        6,    7,    1,    1,    1,    1,    1,    3,    7,    7,
        7,    7,    7,    7,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    1,    3,    1,    1,    8,    6,    6,
        7,    7,    7,    6,    8,    8,    8,    8,    8,    8,
        9,    8,    8,    9,    8,    9,    8,    9,    8,    9,
        8,    8,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[361] =
    {   0,
        0,   75,    0,    0,   75,   77,   76,   81,    0,    0,
       82,   84,  750,  751,   86,  751,  723,  751,  722,   80,
      751,  751,  751,  721,   78,  751,   81,   79,   92,  102,
       95,  751,  751,   77,  720,   99,    0,  137,  751,  719,
      136,  677,  679,   80,   58,   90,   68,  680,   77,  679,
      687,  122,  668,  677,  675,  680,  751,  108,  751,  751,
      179,  690,  751,  751,  751,  140,  751,  751,  689,    0,
      751,  751,  751,  166,  751,  751,  751,  751,  751,  751,
      173,  751,    0,  180,  202,  226,  144,  251,  170,  115,
        0,  707,  706,    0,  256,  278,   84,  669,  668,  676,

      668,  665,  660,  669,  658,  670,  657,  672,  659,  665,
      651,  652,  649,  649,  652,  649,  646,    0,  121,  650,
      150,  648,  148,  140,  652,  645,  133,  171,  650,  234,
      661,  660,  701,  204,  751,  271,  186,  231,    0,  267,
      751,    0,  283,  292,  751,  280,  204,  290,  324,  331,
      142,  751,  256,  281,  751,  325,  751,  646,  640,  639,
      640,  638,  649,  633,  647,  631,  632,  644,  639,  627,
      188,  641,  639,  635,  627,  633,  636,  622,  626,    0,
      627,  624,  614,  612,  614,  605,  610,  596,  593,  590,
      602,  591,  583,  582,  582,  565,  577,  751,  211,    0,

      751,  285,    0,  339,  353,  362,  751,  373,  377,  289,
      751,  295,  296,  329,  751,  751,  751,  362,  330,  558,
      544,  497,  492,  501,  497,  498,  484,  496,  490,  481,
      489,  478,  485,  479,  470,  474,  469,  469,  468,  465,
      473,  463,  467,  472,  471,  469,  459,  464,  445,  457,
      464,  398,  463,  389,  508,  403,  413,  751,  751,  335,
      751,  367,  361,  751,  368,  446,  449,  446,  440,  446,
      436,  444,  451,  438,  439,  438,  429,  436,  422,  430,
      425,  429,  426,  428,  412,  421,  423,  414,  417,  251,
        0,  325,    0,  751,  751,  751,  751,  258,  422,  418,

      413,  405,  398,  413,  411,  395,  395,  407,  407,  403,
      403,  396,  418,  421,  389,  399,  382,  399,  400,  384,
      398,  397,  391,  379,  364,  368,  363,  319,  369,  349,
      325,  331,  307,  291,  261,  222,  201,  211,  172,  148,
       83,   54,   43,  751,  562,  571,  580,  589,  593,  602,
      611,  620,  629,  638,  642,  648,  655,  664,  668,  670
    } ;

static const flex_int16_t yy_def[361] =
    {   0,
      344,    1,  345,  345,  346,  346,  347,  347,  345,  345,
      348,  348,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  349,  344,  344,  344,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  344,  344,  344,  344,
      344,  350,  344,  344,  344,  351,  344,  344,  352,  353,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  354,  344,  344,  344,  344,  344,  344,  344,
      355,  344,  344,  349,  344,  344,  349,  349,  349,  349,

      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  344,
      350,  350,  344,  351,  344,  356,  352,  357,  353,  344,
      344,  354,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  355,  344,  344,  344,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  358,  344,  351,  359,

      344,  352,  360,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      358,  356,  351,  357,  352,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  351,
      253,  352,  255,  344,  344,  344,  344,  349,  349,  349,

      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  252,  254,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  351,  352,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,    0,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344
    } ;

static const flex_int16_t yy_nxt[828] =
    {   0,
       14,   15,   16,   15,   17,   18,   14,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       31,   31,   32,   33,   34,   35,   36,   32,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   38,   14,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   37,   49,   37,   50,   37,
       37,   37,   37,   51,   52,   53,   54,   55,   56,   37,
       37,   37,   57,   58,   59,   60,   61,   65,   68,   65,
       66,   62,   66,   68,   71,   69,   71,   74,   77,   74,
       69,   79,   72,   73,   72,   73,   79,   81,   81,   81,

       81,   92,   75,   76,   82,   78,   76,   80,  118,   83,
      110,   84,  118,   86,   86,   86,   86,   76,   84,  111,
       85,   85,   85,   86,   75,   93,  115,   88,  107,  116,
      118,   87,   89,   78,   88,  108,   90,  119,   95,   89,
       95,  109,  158,   90,   91,  135,  343,   88,  112,  159,
      113,   87,  153,   89,   88,   96,   96,   96,   96,  114,
       89,   90,  148,  148,   97,   98,   99,   74,   90,   74,
      100,   91,  101,  153,  102,  103,  104,  122,  123,  179,
      130,   77,   74,  216,  136,  131,  180,  124,  188,  192,
      125,   81,   81,   81,   81,  201,  342,  193,  143,  143,

      143,  143,  186,  189,  182,  140,  141,  151,  216,  135,
      141,  152,  144,  145,  183,  184,  135,  145,   84,  187,
       85,   85,   85,   86,  341,  140,  141,  194,  151,  195,
      138,  141,  144,  145,   88,  130,  152,   74,  145,  146,
      131,  212,   84,  147,   86,   86,   86,   86,  136,  202,
      202,  202,  230,  231,   88,  252,  135,   95,   88,   95,
      146,  340,  212,   89,  149,  339,  149,   90,  147,  150,
      150,  150,  150,  198,   96,   96,   96,   96,   88,  156,
      204,  156,  204,  338,   89,  205,  205,  205,  205,  199,
      199,  199,   90,  217,  201,  313,   96,   96,   96,   96,

      203,  143,  143,  143,  143,  208,  315,  208,  148,  148,
      209,  209,  209,  209,  217,  206,  207,  210,  218,  316,
      207,  211,  219,  157,  135,  337,  156,  213,  156,  254,
      258,  214,  259,  260,  201,  206,  207,  261,  210,  218,
      200,  207,  150,  150,  150,  150,  211,  219,  213,  150,
      150,  150,  150,  259,  260,  258,  214,  205,  205,  205,
      205,  118,  261,  313,  215,  336,  262,  265,  215,  314,
      157,  205,  205,  205,  205,  256,  294,  256,  201,  335,
      257,  257,  257,  257,  215,  118,  141,  262,  265,  215,
      141,  209,  209,  209,  209,  209,  209,  209,  209,  263,

      198,  294,  296,  264,  295,  297,  141,  292,  292,  292,
      145,  141,  334,  314,  145,  118,  290,  290,  290,  180,
      263,  257,  257,  257,  257,  295,  297,  296,  264,  118,
      145,  257,  257,  257,  257,  145,  328,  328,  328,  329,
      329,  329,  118,  118,  333,  332,  207,  331,  330,  118,
      207,  118,  118,  118,  327,  326,  118,  325,  203,  324,
      118,  323,  322,  321,  320,  319,  207,  200,  135,  318,
      317,  207,  118,  312,  311,  310,  118,  118,  118,  118,
      180,  291,  291,  291,  291,  118,  309,  308,  118,  118,
      180,  291,  291,  291,  291,  291,  291,  307,  306,  305,

      304,  303,  302,  301,  300,  299,  298,  136,  133,  118,
      289,  291,  291,  291,  291,  291,  291,  201,  288,  118,
      287,  286,  285,  284,  283,  282,  293,  293,  293,  293,
      180,  281,  280,  279,  278,  180,  293,  293,  293,  293,
      293,  293,  277,  276,  275,  274,  118,  118,  273,  272,
      271,  270,  138,  269,  268,  118,  293,  293,  293,  293,
      293,  293,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   94,   94,

       94,   94,  132,  267,  132,  132,  132,  132,  132,  132,
      132,  134,  266,  134,  134,  134,  134,  134,  134,  134,
      137,  133,  137,  250,  137,  137,  137,  137,  137,  139,
      249,  139,  139,  180,  139,  139,  139,  139,  142,  248,
      142,  142,  142,  142,  142,  142,  142,  154,  154,  134,
      134,  134,  247,  134,  246,  245,  134,  137,  137,  244,
      137,  243,  242,  137,  251,  241,  251,  251,  251,  251,
      251,  251,  251,  253,  253,  255,  255,  240,  239,  238,
      237,  180,  236,  118,  235,  234,  118,  118,  233,  232,
      180,  118,  229,  118,  228,  227,  226,  225,  224,  223,

      222,  221,  220,  197,  133,  133,  196,  191,  190,  185,
      181,  178,  118,  177,  176,  175,  174,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  155,  155,  138,  133,  129,  128,  127,  126,  121,
      120,  117,  106,  105,   78,   75,   76,   76,   75,  344,
       13,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344
    } ;

static const flex_int16_t yy_chk[828] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    5,    7,    6,
        5,    2,    6,    8,   11,    7,   12,   15,   20,   15,
        8,   25,   11,   11,   12,   12,   27,   28,   28,   28,

       28,   34,   34,   25,   29,   20,   27,   27,  343,   29,
       45,   31,  342,   31,   31,   31,   31,   29,   30,   45,
       30,   30,   30,   30,   36,   36,   47,   31,   44,   47,
       49,   30,   31,   58,   30,   44,   31,   49,   38,   30,
       38,   44,   97,   30,   30,   66,  341,   31,   46,   97,
       46,   30,   90,   31,   30,   38,   38,   38,   38,   46,
       30,   31,   87,   87,   41,   41,   41,   74,   30,   74,
       41,   30,   41,   90,   41,   41,   41,   52,   52,  119,
       61,   58,   61,  151,   66,   61,  119,   52,  124,  127,
       52,   81,   81,   81,   81,  137,  340,  127,   84,   84,

       84,   84,  123,  124,  121,   81,   81,   89,  151,  134,
       81,   89,   84,   84,  121,  121,  199,   84,   85,  123,
       85,   85,   85,   85,  339,   81,   81,  128,   89,  128,
      137,   81,   84,   84,   85,  130,   89,  130,   84,   85,
      130,  147,   86,   85,   86,   86,   86,   86,  134,  138,
      138,  138,  171,  171,   85,  199,  290,   95,   86,   95,
       85,  338,  147,   86,   88,  337,   88,   86,   85,   88,
       88,   88,   88,  136,   95,   95,   95,   95,   86,   96,
      140,   96,  140,  336,   86,  140,  140,  140,  140,  136,
      136,  136,   86,  153,  202,  290,   96,   96,   96,   96,

      138,  143,  143,  143,  143,  144,  298,  144,  148,  148,
      144,  144,  144,  144,  153,  143,  143,  146,  154,  298,
      143,  146,  154,   96,  328,  335,  156,  148,  156,  202,
      210,  148,  212,  213,  292,  143,  143,  213,  146,  154,
      136,  143,  149,  149,  149,  149,  146,  154,  148,  150,
      150,  150,  150,  212,  213,  210,  148,  204,  204,  204,
      204,  334,  213,  328,  150,  333,  214,  219,  150,  292,
      156,  205,  205,  205,  205,  206,  260,  206,  329,  332,
      206,  206,  206,  206,  150,  331,  205,  214,  219,  150,
      205,  208,  208,  208,  208,  209,  209,  209,  209,  218,

      252,  260,  263,  218,  262,  265,  205,  254,  254,  254,
      209,  205,  330,  329,  209,  327,  252,  252,  252,  326,
      218,  256,  256,  256,  256,  262,  265,  263,  218,  325,
      209,  257,  257,  257,  257,  209,  313,  313,  313,  314,
      314,  314,  324,  323,  322,  321,  257,  320,  319,  318,
      257,  317,  316,  315,  312,  311,  310,  309,  254,  308,
      307,  306,  305,  304,  303,  302,  257,  252,  253,  301,
      300,  257,  299,  289,  288,  287,  286,  285,  284,  283,
      282,  253,  253,  253,  253,  281,  280,  279,  278,  277,
      276,  253,  253,  253,  253,  253,  253,  275,  274,  273,

      272,  271,  270,  269,  268,  267,  266,  253,  251,  250,
      249,  253,  253,  253,  253,  253,  253,  255,  248,  247,
      246,  245,  244,  243,  242,  241,  255,  255,  255,  255,
      240,  239,  238,  237,  236,  235,  255,  255,  255,  255,
      255,  255,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  255,  224,  223,  222,  255,  255,  255,  255,
      255,  255,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  349,  349,

      349,  349,  350,  221,  350,  350,  350,  350,  350,  350,
      350,  351,  220,  351,  351,  351,  351,  351,  351,  351,
      352,  197,  352,  196,  352,  352,  352,  352,  352,  353,
      195,  353,  353,  194,  353,  353,  353,  353,  354,  193,
      354,  354,  354,  354,  354,  354,  354,  355,  355,  356,
      356,  356,  192,  356,  191,  190,  356,  357,  357,  189,
      357,  188,  187,  357,  358,  186,  358,  358,  358,  358,
      358,  358,  358,  359,  359,  360,  360,  185,  184,  183,
      182,  181,  179,  178,  177,  176,  175,  174,  173,  172,
      170,  169,  168,  167,  166,  165,  164,  163,  162,  161,

      160,  159,  158,  133,  132,  131,  129,  126,  125,  122,
      120,  117,  116,  115,  114,  113,  112,  111,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,
       98,   93,   92,   69,   62,   56,   55,   54,   53,   51,
       50,   48,   43,   42,   40,   35,   24,   19,   17,   13,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[55] =
    {   0,
1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 5 "scanner.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

static char* xstrdup(const char* s){
    if(!s) return NULL;
    size_t n=strlen(s)+1; char* p=(char*)malloc(n); if(p) memcpy(p,s,n); return p;
}
static char* xsubstr(const char* s, size_t a, size_t b){
    if(!s||b<a) return xstrdup("");
    size_t n=b-a; char* p=(char*)malloc(n+1); if(!p) return NULL;
    memcpy(p,s+a,n); p[n]='\0'; return p;
}
static char* trim(char* s){
    if(!s) return s;
    size_t n=strlen(s);
    size_t i=0; while(i<n && isspace((unsigned char)s[i])) i++;
    size_t j=n; while(j>i && isspace((unsigned char)s[j-1])) j--;
    size_t m=j-i; memmove(s, s+i, m); s[m]='\0'; return s;
}

typedef struct Symbol {
    char* name;
    char* type;            /* e.g., int, float, char*, struct X */
    char* dimensions;      /* e.g., [10][20] */
    int   frequency;       /* number of appearances */
    char* return_type;     /* for functions */
    char* param_lists;     /* concatenated lists observed in function calls or declarations */
    int   is_function;     /* boolean */
    struct Symbol* next;   /* chaining in hash bucket */
} Symbol;

#define SYM_HASH_SIZE 211
static Symbol* symtab[SYM_HASH_SIZE];

static unsigned long djb2(const char* str){
    unsigned long hash = 5381; int c;
    while((c = (unsigned char)*str++)) hash = ((hash << 5) + hash) + c;
    return hash;
}
static Symbol* sym_lookup(const char* name){
    unsigned long h = djb2(name) % SYM_HASH_SIZE;
    Symbol* s = symtab[h];
    while(s){ if(strcmp(s->name, name)==0) return s; s=s->next; }
    return NULL;
}
static Symbol* sym_insert(const char* name){
    unsigned long h = djb2(name) % SYM_HASH_SIZE;
    Symbol* s = (Symbol*)calloc(1, sizeof(Symbol));
    s->name = xstrdup(name);
    s->frequency = 0;
    s->next = symtab[h];
    symtab[h] = s;
    return s;
}
static Symbol* sym_touch(const char* name){
    Symbol* s = sym_lookup(name);
    if(!s) s = sym_insert(name);
    s->frequency++;
    return s;
}
static void sym_set_type(Symbol* s, const char* type){
    if(!s) return;
    if(s->type) free(s->type);
    s->type = xstrdup(type);
}
static void sym_set_return(Symbol* s, const char* r){
    if(!s) return;
    if(s->return_type) free(s->return_type);
    s->return_type = xstrdup(r);
}
static void sym_append_dims(Symbol* s, const char* dims){
    if(!s || !dims) return;
    size_t old = s->dimensions ? strlen(s->dimensions) : 0;
    size_t add = strlen(dims);
    char* p = (char*)malloc(old + add + 1);
    if(!p) return;
    if(old){ memcpy(p, s->dimensions, old); free(s->dimensions); }
    memcpy(p+old, dims, add);
    p[old+add]='\0';
    s->dimensions = p;
}
static void sym_append_params(Symbol* s, const char* params){
    if(!s || !params) return;
    const char* sep = s->param_lists ? " ; " : "";
    size_t old = s->param_lists ? strlen(s->param_lists) : 0;
    size_t add = strlen(sep) + strlen(params);
    char* p = (char*)malloc(old + add + 1);
    if(!p) return;
    if(old){ memcpy(p, s->param_lists, old); free(s->param_lists); }
    memcpy(p+old, sep, strlen(sep));
    memcpy(p+old+strlen(sep), params, strlen(params));
    p[old+add]='\0';
    s->param_lists = p;
}

typedef struct Constant {
    char* var_name;  /* For #define NAME value, or variable name for other constants */
    int   line;
    char* value;     /* literal text */
    char* type;      /* "int", "float", "char", "string", "hex", "oct", "bin", "macro" */
} Constant;

static Constant* consts = NULL;
static size_t nconsts = 0, capconsts = 0;

static void const_add(const char* var, int line, const char* val, const char* type){
    if(nconsts == capconsts){
        capconsts = capconsts ? capconsts*2 : 64;
        consts = (Constant*)realloc(consts, capconsts * sizeof(Constant));
    }
    consts[nconsts].var_name = xstrdup(var ? var : "-");
    consts[nconsts].line = line;
    consts[nconsts].value = xstrdup(val ? val : "");
    consts[nconsts].type = xstrdup(type ? type : "");
    nconsts++;
}

static int in_declaration = 0;
static char last_type[256] = {0};
static char last_ident[256] = {0};
static int last_was_ident = 0;
static int array_capture_for_ident = 0;
static int brace_depth = 0;
static int assignment_context = 0;  /* Track if we're in an assignment */
static char pending_var[256] = {0}; /* Variable name for pending constant assignment */

static void start_declaration(const char* t){
    in_declaration = 1;
    last_type[0]='\0';
    if(t){ strncat(last_type, t, sizeof(last_type)-1); }
}
static void add_type_token(const char* t){
    if(last_type[0]) strncat(last_type, " ", sizeof(last_type)-1);
    strncat(last_type, t, sizeof(last_type)-1);
}
static void end_declaration(){
    in_declaration = 0;
    last_type[0]='\0';
    assignment_context = 0;
    pending_var[0] = '\0';
}

static int paren_depth = 0;
static int capturing_args = 0;
static char* arg_buffer = NULL;
static size_t arg_cap = 0, arg_len = 0;
static Symbol* current_func_sym = NULL;

static void args_begin(Symbol* s){
    capturing_args = 1; paren_depth = 1; arg_len = 0;
    if(!arg_buffer){ arg_cap = 256; arg_buffer = (char*)malloc(arg_cap); }
    current_func_sym = s;
}
static void args_push_char(int c){
    if(!capturing_args) return;
    if(arg_len + 2 > arg_cap){
        arg_cap *= 2;
        arg_buffer = (char*)realloc(arg_buffer, arg_cap);
    }
    arg_buffer[arg_len++] = (char)c;
    arg_buffer[arg_len] = '\0';
}
static void args_end(){
    if(capturing_args && current_func_sym){
        /* remove trailing ) if present */
        if(arg_len && arg_buffer[arg_len-1] == ')'){ arg_buffer[arg_len-1] = '\0'; }
        char* s = xstrdup(arg_buffer);
        trim(s);
        sym_append_params(current_func_sym, s);
        current_func_sym->is_function = 1;
        free(s);
    }
    capturing_args = 0; paren_depth = 0; arg_len = 0; current_func_sym = NULL;
}

static void print_token(const char* kind, const char* lexeme){
    printf("[line %d] %-12s : %s\n", yylineno, kind, lexeme);
}

static const char* classify_int(const char* s){
    if(!s) return "int";
    if(strlen(s) > 2 && s[0]=='0' && (s[1]=='x'||s[1]=='X')) return "hex";
    if(strlen(s) > 2 && s[0]=='0' && (s[1]=='b'||s[1]=='B')) return "bin";
    if(s[0]=='0' && strlen(s)>1) return "oct";
    return "int";
}

#define YY_USER_ACTION /* placeholder */

#line 962 "lex.yy.c"

#line 964 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STRING 2
#define CHARLIT 3
#define PP 4
#define FUNCARGS 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 222 "scanner.l"


#line 1192 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 345 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 751 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 224 "scanner.l"
{
    print_token("PREPROC", yytext);
    char* tmp = xstrdup(yytext);
    char* p = tmp;
    while(*p==' '||*p=='\t') p++;
    if(*p=='#'){ p++; }
    while(*p==' ') p++;
    if(strncmp(p,"define",6)==0 && isspace((unsigned char)p[6])){
        p+=6; while(*p==' ') p++;
        char namebuf[256]={0};
        int i=0;
        while(*p && (isalnum((unsigned char)*p) || *p=='_')){
            if(i<255) namebuf[i++]=*p;
            p++;
        }
        namebuf[i]='\0';
        while(*p==' '||*p=='\t') p++;
        char* val = trim(p);
        if(val && namebuf[0]){
            const_add(namebuf, yylineno, val, "macro");
        }
    }
    free(tmp);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 249 "scanner.l"
{ /* ignore */ }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 250 "scanner.l"
{ /* newline handled by %option yylineno */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 252 "scanner.l"
{ /* ignore */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 254 "scanner.l"
{ BEGIN(COMMENT); int depth=1; int c1,c2;
             while(depth>0){
                c1 = input();
                if(c1==EOF){ fprintf(stderr,"[line %d] ERROR: Unterminated comment\n", yylineno); BEGIN(INITIAL); break; }
                if(c1=='\n'){ /* yylineno auto increments via flex */ }
                if(c1=='/'){
                    c2 = input();
                    if(c2=='*'){ depth++; }
                    else if(c2!=EOF){ unput(c2); }
                } else if(c1=='*'){
                    c2 = input();
                    if(c2=='/'){ depth--; }
                    else if(c2!=EOF){ unput(c2); }
                }
             }
             BEGIN(INITIAL);
           }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 272 "scanner.l"
{ BEGIN(STRING); yyless(0); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 273 "scanner.l"
{
             print_token("STRING", yytext);
             const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
             const_add(var_name, yylineno, yytext, "string");
             if(assignment_context) assignment_context = 0;
             BEGIN(INITIAL);
           }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 280 "scanner.l"
{ /* continued line inside string - treat as part of string */ }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 281 "scanner.l"
{ fprintf(stderr,"[line %d] ERROR: Unterminated string literal\n", yylineno-1); BEGIN(INITIAL); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 282 "scanner.l"
{ /* consume */ }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 284 "scanner.l"
{ BEGIN(CHARLIT); yyless(0); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 285 "scanner.l"
{
             print_token("CHAR", yytext);
             const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
             const_add(var_name, yylineno, yytext, "char");
             if(assignment_context) assignment_context = 0;
             BEGIN(INITIAL);
           }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 292 "scanner.l"
{ fprintf(stderr,"[line %d] ERROR: Unterminated char literal\n", yylineno-1); BEGIN(INITIAL); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 293 "scanner.l"
{ /* consume */ }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 295 "scanner.l"
{
    print_token("KEYWORD", yytext);
    last_was_ident = 0;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 300 "scanner.l"
{
    print_token("TYPE", yytext);
    if(!in_declaration) start_declaration(yytext);
    else add_type_token(yytext);
    last_was_ident = 0;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 307 "scanner.l"
{
    print_token("IDENT", yytext);
    Symbol* s = sym_touch(yytext);
    strncpy(last_ident, yytext, sizeof(last_ident)-1);
    last_ident[sizeof(last_ident)-1]='\0';
    last_was_ident = 1;
    array_capture_for_ident = 1;
    if(in_declaration){
        if(!s->type && last_type[0]) sym_set_type(s, last_type);
    }
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 319 "scanner.l"
{ 
    print_token("NUMBER", yytext); 
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, "hex"); 
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0; 
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 326 "scanner.l"
{ 
    print_token("NUMBER", yytext); 
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, "bin"); 
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0; 
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 333 "scanner.l"
{ 
    print_token("NUMBER", yytext); 
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, "float"); 
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0; 
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 340 "scanner.l"
{ 
    print_token("NUMBER", yytext); 
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, "float"); 
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0; 
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 347 "scanner.l"
{ 
    print_token("NUMBER", yytext); 
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, "float"); 
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0; 
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 354 "scanner.l"
{ 
    print_token("NUMBER", yytext); 
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, "float"); 
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0; 
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 361 "scanner.l"
{ 
    print_token("NUMBER", yytext); 
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, "oct"); 
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0; 
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 368 "scanner.l"
{ 
    print_token("NUMBER", yytext); 
    const char* var_name = (assignment_context && pending_var[0]) ? pending_var : "-";
    const_add(var_name, yylineno, yytext, classify_int(yytext)); 
    if(assignment_context) assignment_context = 0;
    last_was_ident = 0; 
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 376 "scanner.l"
{
            print_token("PUNCT", yytext);
            if(last_was_ident){
                Symbol* s = sym_lookup(last_ident);
                if(!s) s = sym_touch(last_ident);
                if(in_declaration || brace_depth == 0){
                    s->is_function = 1;
                    if(last_type[0]) sym_set_return(s, last_type);
                }
                args_begin(s);
                BEGIN(FUNCARGS);
            }
            last_was_ident = 0;
         }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 390 "scanner.l"
{ /* collect raw text inside args */ for(size_t i=0;i<yyleng;i++) args_push_char(yytext[i]); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 391 "scanner.l"
{ args_push_char('('); paren_depth++; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 392 "scanner.l"
{ args_push_char(')'); paren_depth--; if(paren_depth==0){ args_end(); BEGIN(INITIAL);} }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 393 "scanner.l"
{ args_push_char('\n'); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 395 "scanner.l"
{ print_token("PUNCT", yytext); last_was_ident = 0; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 397 "scanner.l"
{ print_token("PUNCT", yytext); last_was_ident = 0; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 398 "scanner.l"
{ print_token("PUNCT", yytext); last_was_ident = 0; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 399 "scanner.l"
{
            print_token("PUNCT", yytext);
            if(array_capture_for_ident){
                Symbol* s = sym_lookup(last_ident);
                if(s) sym_append_dims(s, yytext);
            }
            last_was_ident = 0;
         }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 408 "scanner.l"
{ 
    print_token("PUNCT", yytext); 
    array_capture_for_ident = 0; 
    if(in_declaration) end_declaration(); 
    last_was_ident = 0; 
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 414 "scanner.l"
{ print_token("PUNCT", yytext); last_was_ident = 0; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 415 "scanner.l"
{ print_token("PUNCT", yytext); brace_depth++; if(in_declaration) end_declaration(); last_was_ident = 0; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 416 "scanner.l"
{ print_token("PUNCT", yytext); brace_depth--; last_was_ident = 0; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 417 "scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 419 "scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 420 "scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 421 "scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 422 "scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 423 "scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 424 "scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 425 "scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 426 "scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 427 "scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 428 "scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 429 "scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 430 "scanner.l"
{ print_token("OP", yytext); last_was_ident = 0; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 431 "scanner.l"
{ 
    print_token("OP", yytext); 
    if(last_was_ident) {
        assignment_context = 1;
        strncpy(pending_var, last_ident, sizeof(pending_var)-1);
        pending_var[sizeof(pending_var)-1] = '\0';
    }
    last_was_ident = 0; 
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 441 "scanner.l"
{
            fprintf(stderr, "[line %d] ERROR: Invalid token '%s'\n", yylineno, yytext);
          }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(CHARLIT):
case YY_STATE_EOF(PP):
case YY_STATE_EOF(FUNCARGS):
#line 445 "scanner.l"
{
            printf("\n************************************* SYMBOL TABLE *************************************\n");
            printf("%-20s %-15s %-12s %-10s %-15s %s\n", "Name", "Type", "Dimensions", "Frequency", "Return Type", "Parameters Lists in Function call");
            for(int i=0;i<SYM_HASH_SIZE;i++){
                for(Symbol* s=symtab[i]; s; s=s->next){
                    printf("%-20s %-15s %-12s %-10d %-15s %s\n",
                        s->name,
                        s->type ? s->type : "-",
                        s->dimensions ? s->dimensions : "-",
                        s->frequency,
                        s->return_type ? s->return_type : (s->is_function ? "unknown" : "-"),
                        s->param_lists ? s->param_lists : "-"
                    );
                }
            }
            printf("\n************************************* CONSTANT TABLE *************************************\n");
            printf("%-20s %-10s %-30s %s\n", "Variable Name", "Line No.", "Value", "Type");
            for(size_t i=0;i<nconsts;i++){
                printf("%-20s %-10d %-30s %s\n",
                    consts[i].var_name ? consts[i].var_name : "-",
                    consts[i].line,
                    consts[i].value ? consts[i].value : "",
                    consts[i].type ? consts[i].type : ""
                );
            }
            return 0;
          }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 473 "scanner.l"
ECHO;
	YY_BREAK
#line 1723 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 345 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 345 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 344);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 473 "scanner.l"


int main(int argc, char** argv){
    if(argc > 1){
        FILE* f = fopen(argv[1], "r");
        if(!f){ perror("fopen"); return 1; }
        yyin = f;
    }
    yylex();
    return 0;
}
